# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
safe: true


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 乘风破浪

description: 描述 Stylish Jekyll Theme
author:
  name: kingizz
  email: 517821485@qq.com
  github: zziking
  weibo: kingizz
  bio: 千里不辞行路远<br>时光早晚到天涯<br>长风破浪会有时<br>直挂云帆济沧海<br>
  #email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: 
title: kingizz #sidebar title
kz_full_content_index: false #文章列表是否显示文章的全部内容

comments:
  provider: duoshuo
  duoshuo:
    short_name: kingizz
